### ISSUE TITLE
Dates should match design

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1022]
In the channel list on mobile, "most recent message sent on..." dates display as e.g. "Nov 10, 12:23PM" when they should display as either "Yesterday" or "Nov 10"

See design: https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile-(and-prototype)?node-id=456%3A18822&t=FRJwrcYEsdOlvFPP-0

![image](https://user-images.githubusercontent.com/213678/201489121-3cbe95d5-18c8-4715-8ce8-b5c418937213.png)

**Comment by josephlacey** [comment]
@holmesworcester I've submitted an initial fix for this, but as always with time handling there's some lingering questions,

* I've redefined today as within the same 24hr date period, i.e matching date between 00:00 to 23:59.  The previous iteration had today defined as rolling, so within the last 24 hours regardless of the clock time date.  Under the rolling model a message sent in the afternoon the previous clock-time day would render the next morning as a time rather than 'Yesterday'.  That seems fine, but the day after would render that same message as 'Yesterday' when it was from two clock-time days ago, which could be confusing.
  * Note that 'Yesterday' is a static string and not internationalized, but that seems like a much larger project.
*  Yesterday is the same as today except the preceding 24hr date period.  This wasn't defined before but if we want to switch back to rolling 24hr periods, this would be redefined as between 24-48hrs ago.
* I've switched to locale specific date and time rendering, but the default formatting for [shortcuts from Luxon](https://moment.github.io/luxon/docs/manual/formatting.html#tolocalestring--strings-for-humans-) doesn't quite match the design.  Matching the design exactly seems like it will be hard to get correct across all locales.
  * For the US locale, the current patch renders times for messages sent today with a space after the time and with the meridian in all caps.  Design shows no space and lowercase meridian.  For locales that use a 24hr representation, it would render in 24-hr time without a meridian.
  * For the US locale, the current patch renders the date for messages before yesterday with the full 4-digit year.  Design shows US formatting with a 2-digit year.  Not sure what that will look like in other locales, but I can render and send some examples.

![Screenshot_20230322-085517_Debug Quiet](https://user-images.githubusercontent.com/794622/226971931-199f3837-b3d6-4a4d-88e7-2e0c75333151.png)

**Comment by holmesworcester** [comment]
I think the defaults are fine and agree with the other decisions. This looks great!

**Comment by josephlacey** [comment]
@holmesworcester Per the conversation today, here's the mobile date issue with a PR if you want to move it into the Next Sprint.

**Comment by kingalg** [comment]
Done.
