### ISSUE TITLE
Turning off notifications resets chosen notification sound

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1117]
When you turn off notifications and turn them back on, the notification sound has been reset back to the default.

Steps:
1. Change notification sound
2. Turn off notifications
3. Turn them back on

Expected: notification sound is the same

Actual: notification sound changes back to the default

**Comment by holmesworcester** [comment]
@josephlacey this might be a good starter issue!

**Comment by josephlacey** [comment]
I dug into this issue a bit.  The data model for the notifications sounds currently treats the 'Play a sound when receiving a notification' checkbox as a sound option, namely one called `none`.  If the sound option isn't set to `none`, then the 'Play a sound when receiving a notification' box is checked, and you can selected one of the other options.  If it is `none`, the box is unchecked and the other options are greyed out.  The logic is elegant, but under this data model I'm not seeing a way to save both `none`  and which of the other four chosen sounds you've selected simultaneously.  The solution to solve this bug seems to be separate the preferred sound from whether to play it or not, but as far as I can tell adding a new setting is a more significant refactor that may seems touch more than just the desktop version.

**Comment by holmesworcester** [comment]
would another solution be to make the different sound options a list where 'none' is an item in the list? Like can we make the form correspond to the data as a quicker fix?

**Comment by josephlacey** [comment]
PR #1252 doesn't include any new tests because this only changes the presentation.  The existing tests should remain sufficient.

**Comment by josephlacey** [comment]
Adding a screenshot of the new notifications settings UI

![Sound-when-receiving-a-notifcation](https://user-images.githubusercontent.com/794622/221078626-6cb046ff-9562-426f-a860-fefdf04aabe0.png)

**Comment by holmesworcester** [comment]
Looks good.

**Comment by kingalg** [comment]
Version: 1.1.0-alpha.3

It's working.
