### ISSUE TITLE
User should be able to paste an invite link or URI on join screen

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1283]
As a fallback, if a user receives an invite link and cannot open it for some reason, or if they are confused, they should be able to paste it in the "invite code" field on the join screen and everything should work the same as if they had opened the link.

**Comment by EmiM** [comment]
How 'userproof" this feature should be? Can we assume that the whole URL will be pasted correctly?
`https://tryquiet.org/join?code=bb5wacaftixjl3yhq2cp3ls2ife2e5wlwct3hjlb4lyk4iniypmgoasd`

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1376

**Comment by holmesworcester** [comment]
I think we should show a helpful error if it's invalid. Is that what you mean?

**Comment by holmesworcester** [comment]
The error message can be a separate issue. Can you make one if needed?

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1376

I meant that if we are requiring user to paste full proper invitation URL -> https://tryquiet.org/join?code=bb5wacaftixjl3yhq2cp3ls2ife2e5wlwct3hjlb4lyk4iniypmgoasd, not e.g url lacking protocol -> tryquiet.org/join?code=bb5wacaftixjl3yhq2cp3ls2ife2e5wlwct3hjlb4lyk4iniypmgoasd or something similar. 

Right now I implemented it that proper URL is required which should not be a problem since this is what we share as an invitation link.
If the url (or part of the url like code itself) is invalid then I display just `Please check your invitation code and try again`.
I also removed `Invitation code is too long` and `Invitation code is too short` errors since I am not sure if this information is valuable for the user.

**Comment by EmiM** [comment]
Mobile: https://github.com/TryQuiet/quiet/pull/1383

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.26
Done (with bug on macOS that will be fixed in an issue #1448  already waiting to be marge).
