### ISSUE TITLE
User should be able to share invite link

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1284]
In earlier tickets in this sprint we've built nice WhatsApp-style invite links. Now let's make it possible for users to share them. 

designs: https://www.figma.com/file/y8h6w8PYR9jyI3zjYHL9Cl/Mobile-%2B-desktop-%2B-prototypes?node-id=1430%3A49444&t=Rda4DFJRzND1fEIl-4

Note: these designs imply a unified design for mobile and desktop settings. The code doesn't have to be unified but maybe we should explore that. But making at least the designs unified will make them easier to maintain and reason about at a design level.

NOTE: Just do #1290 as part of this work since it's so related and easy.

**Comment by siepra** [comment]
Related PR (mobile part) https://github.com/TryQuiet/quiet/pull/1367

**Comment by holmesworcester** [comment]
@Kacper-RF we don't have to redesign all the screens as part of this ticket. we just need a way to copy the invite link (instead of the "invite code")

**Comment by Kacper-RF** [comment]
@holmesworcester OK understand, but do we want totally resign of possibility to join community by  `invite code` ? 
At this moment i did something like that, with another tab(with some design consistency similar to invite a friend tab) in settings with possibility to see and copy link:
Please let me know, what do You think about it.
![image](https://user-images.githubusercontent.com/111343884/229070877-fad5daf3-0a1a-4a80-a867-47cf8c908c5f.png)

**Comment by holmesworcester** [comment]
Yes this should replace invite a friend and the name of the tab should be 'invite a friend'

We don't have to give people copy/pasteable codes anymore

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.26

QR code tab is implemented nicely on desktop and this part is done.

I've got a question @Kacper-RF  @holmesworcester about "Invite a friend" - I understand that now we should have design that Kacper mentioned in above comments. Looks like link in this design is clickable. In current version it's not - we have a link instead of a code but it's still design similar to previous one. For me it's not that important because user that can see this tab already is in this community so he is interested in copying link for other person not entering it but I want to make sure that we have what we agreed upon in designs. Currently it looks like this:
<img width="537" alt="Screenshot 2023-04-14 at 12 32 58" src="https://user-images.githubusercontent.com/68909168/232021297-112883eb-7915-4f19-972f-c8bdd317c569.png">
<img width="539" alt="Screenshot 2023-04-14 at 12 33 07" src="https://user-images.githubusercontent.com/68909168/232021327-3a1c9c4a-d362-4d1d-9499-1957a3b00114.png">

**Comment by holmesworcester** [comment]
Not-clickable is correct.

**Comment by kingalg** [comment]
Great, co I'm closing this.
