### ISSUE TITLE
User should be able to install APK 

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1342]
Some users with degoogled phones don't want to install Aurora so until we exist in f-droid there's no way for them to try the app. We should link to the APK somewhere so they can get the app! Ideally the APK would live in Github releases.

Here's the new design to include an APK link:

https://tryquiet.webflow.io/#Downloads

[tryquiet.webflow (4).zip](https://github.com/TryQuiet/quiet/files/12081626/tryquiet.webflow.4.zip)

**Note, update the following text in the design:** "Keep your team within reach at all times with the Quiet app" -> "To create and join communities on Quiet, get the app for your device (iOS coming soon!)"

**Comment by holmesworcester** [comment]
Related to: #908 ... in that the APK could be available in our releases, if that was clean and accessible.

**Comment by smaragdus** [comment]
Currently [Aurora Store](https://f-droid.org/en/packages/com.aurora.store) is almost unusable without a Google account because Google rate-limited accounts and search does not work within the app. There are other [sources](https://apkcombo.com/quiet-team-chat-over-tor/com.quietmobile/) for downloads but it would be far better if the APK files are available for download in [releases](https://github.com/TryQuiet/quiet/releases) until [Quiet](https://github.com/TryQuiet/quiet) gets published in [F-Droid](https://f-droid.org/en/).

**Comment by holmesworcester** [comment]
That's helpful. I'll prioritize this.

**Comment by holmesworcester** [comment]
Let's do a design for adding this option to the download buttons on the homepage.

**Comment by holmesworcester** [comment]
@siepra would you like to take this one?

**Comment by siepra** [comment]
In fact we're gonna be shipping **.apks** which is better optimised format introduced as a new standard by Google.
I assume users who're interested in installing the app manually already knows the tools and methods, nevertheless I generated a handy guide on .apks format: https://chat.openai.com/share/348be70c-7215-4ffe-a776-265472722695

@holmesworcester

**Comment by siepra** [comment]
Accordingly to our Slack discussion, the person responsible for rolling out the next production release is supposed to update .apks download url and merge this PR: https://github.com/TryQuiet/quiet/pull/2320

Current release owner: @leblowl
Upcoming release owner: @EmiM

**Comment by holmesworcester** [comment]
> To install an .apks file on an Android device, you typically need to use a third-party tool because Android devices natively recognize and install .apk files but not .apks files directly.

@siepra is this true even for recent versions of Android? Will it continue to be true in the future? This will definitely confuse some people who are used to opening a normal APK directly without other tools. 

Also, do we have an easy option to ship an APK if that is what users ask for?

**Comment by siepra** [comment]
Yes, .apks is not directly supported on device. 
There is a way to ship .apk but we need to start to support a separate flow of building it for we're forced to assemble app bundle for Google Play and it's a separate job. 

There's a significant difference in the way .apk and .abb (.apks) ships resources which in our case is especially important factor because of our unusual usage of tor and nodejs binaries so we should be aware people installing our application from .apk may be facing issues unrelated to our usual work.

The size of the application installed from .apk will also be meaningfully greater than the one installed from .apks.

**Comment by siepra** [comment]
I added a workflow for building .apk and attaching it to releases
https://github.com/TryQuiet/quiet/actions/runs/8085330890

**Comment by holmesworcester** [comment]
Just noting this part:

> Accordingly to our Slack discussion, the person responsible for rolling out the next production release is supposed to update .apks download url and merge this PR: https://github.com/TryQuiet/quiet/pull/2320

**Comment by kingalg** [comment]
Users can download .apk from https://tryquiet.org/
Making sure that with each release we are adding correct .apk file has been added to the prod qa checklist.
