### ISSUE TITLE
Please include an official invite link to the official server on Quiet's official website

### ISSUE THREAD

**Issue by MrLuxuri** [TryQuiet/quiet#1390]
I am coming from Discord and I really like what you folks are doing here with Quiet, but I wonder if you folks have an official server where new users can join and not only be able to talk with the dev team but also keep up with announcements/updates and etc?

Currently it's extremely hard to find an invite, I can't find in the official website, if you folks don't have one, please create an official quiet server, that we new users also have a first community to join and give quiet a test run as well.

**Comment by holmesworcester** [comment]
This is a really good point. I'd like to make this more open. We've hesitated because we don't have features for moderation or user removal yet, so we're trying to keep things to friends and fellow travelers at this point.  

Can you post your email address or Discord name here and I'll send you an invite? You can also email me: h@tryquiet.org

I'm also happy to join your community if you'd like to post an invite, and we could talk there and try out the app.

**Comment by MrLuxuri** [comment]
@holmesworcester Absolutely and thanks for your reply! My email: architsastam@gmail.com

Please do send an invite asap (haha sorry, I am just super duper excited). Thank you and the rest of the team for creating a discord alternative that is p2p and offline-first (possibly?), such a server-less alternative is a dream come true for me!

**Comment by holmesworcester** [comment]
Sending now! Happy May Day!

**Comment by holmesworcester** [comment]
Oh, one more thought: Quiet isn't "offline first" yet but it's a fairly superficial change to make it so you could send and receive messages while offline, since the underlying tech is local-first / offline-first.

**Comment by holmesworcester** [comment]
The solution we decided on for this is to have an email newsletter signup, and invite subscribers in the welcome email.
