### ISSUE TITLE
macos, icon looks quite weird in dock

### ISSUE THREAD

**Issue by mikhailusachev** [TryQuiet/quiet#1438]
Hi, i'm using macos catalina and see something "outstanding".
looks, that icon should be smaller and have more rounded edges.
![Снимок экрана 2023-04-11 в 18 33 00](https://user-images.githubusercontent.com/6051032/231215122-7d8a2ce0-ca0d-4273-ae00-e5da5cd38163.png)

**Comment by holmesworcester** [comment]
@siepra would you like to take this? there's some discussion of this here: https://developer.apple.com/forums/thread/670578

My memory of this is that apple recommends square icons use less than the available space, so that non-square icons don't look smaller than square ones. I would use Apple's own square icons, like System Preferences or Finder, as a guide for size.

**Comment by holmesworcester** [comment]
Here they are:

[Mac OS icons.zip](https://github.com/TryQuiet/quiet/files/11463601/Mac.OS.icons.zip)

**Comment by siepra** [comment]
https://github.com/TryQuiet/quiet/pull/1534

**Comment by siepra** [comment]
![Image](https://github.com/TryQuiet/quiet/assets/15381135/4ce084e1-b745-4351-b653-5a53bc86a035)

**Comment by kingalg** [comment]
Version: 1.4.0-alpha.0

Fixed.

<img width="266" alt="Screenshot 2023-06-26 at 11 44 10" src="https://github.com/TryQuiet/quiet/assets/68909168/6ff3e095-e06d-41c3-af90-f1b388b7d97f">
