### ISSUE TITLE
Joining community doesn't work on MacOS

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1448]
Version: 1.2.0-alpha.26 (forst spotted in 1.2.0-alpha.24)

System: Linux
Browsers check: Chrome, Safari

Users can't join community on MacOS neither from using "join community" website or passing the link directly in the app.
Once the user uses "join community" website Quiet app opens and view "join community" is visible (with nothing in the text field). 
If the user tries to pass the code directly error message "Please check your invitation code and try again" apears.

<img width="583" alt="Screenshot 2023-04-13 at 13 38 24" src="https://user-images.githubusercontent.com/68909168/231747374-f11ceddf-28b8-4f68-b450-750962d8fba2.png">

**Comment by EmiM** [comment]
Using invitation link does not work on MacOS when user have app closed while clicking on the link.
It works fine when app is opened.

Pasting link indeed does not work. It's because of an additional "/":
`https://tryquiet.org/join/#ljvikqpaz5d43kazi7qes6phczm45jqw7upy67ckjgsmc7ewum24r7qd` - doesn't work
`https://tryquiet.org/join#ljvikqpaz5d43kazi7qes6phczm45jqw7upy67ckjgsmc7ewum24r7qd` - works
Fixing.

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/1449

**Comment by kingalg** [comment]
Version: 1.2.0-alpha.28

Fixed. I've joined successfully .
