### ISSUE TITLE
Deleting channel can be slow, user sees no feedback

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1500]
Right now deleting a channel with many messages can take some time, and there is no user feedback. 

Ideally the channel should disappear right away and deletion should happen async in the background. If not possible, we should show a spinner. But I'd really like to not lock up the UI for this.

**Comment by Kacper-RF** [comment]
@holmesworcester 
I talked with Bartek about this problem, and we have similar solution but little bit more secure.

Deleting firstly from fronted its little bit risky, because if user will close app he will stop deletion process on backend and it can have unpredictable impact on app in future, after restart for example.

So maybe immediately after clicking on deletion button:
1.Move user to general channel
2.Reduce opacity of deleting channel
3.Block possibility to click on this channel.
4.After deletion part in backend, saga will remove channel with messages from frontend layer 

We won't block UI by this approach and give better UX
 
Let me know what do You think about this idea

**Comment by holmesworcester** [comment]
Sounds great. And for deleting general?

**Comment by Kacper-RF** [comment]
At the moment for general channel deletion we have spinner

https://user-images.githubusercontent.com/111343884/236823385-ab98edc1-09a2-456d-bd02-1feb22f046ac.mp4

**Comment by holmesworcester** [comment]
"Fetching channel messages" is a confusing message. "Loading channel" might work if we need an all-purpose message, but "Deleting channel" would be better.

**Comment by Kacper-RF** [comment]
Delay after clicking on deletion is only to simulate situation with lot of stuff on channel 

https://github.com/TryQuiet/quiet/assets/111343884/5375b031-76fe-4f54-aa7a-94fe73695710

**Comment by kingalg** [comment]
Version: 1.2.1-alpha.3
For deleting general channel I see "Deleting channel" spinner as planned.
I've tested for channels with more messages (including several pictures and big files) and it was quite fast. We may want to experiment with spam bot again in the near future.
