### ISSUE TITLE
Introduce nest to backend

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#1574]

**Comment by Kacper-RF** [comment]
Most of the time was spent on initializing the modules correctly and fact that libp2p needs to have certs that are available only after user registration which happens during app working.

We do not have access to some data at the backend initialization stage (and even pattern with custom async providers didn't work in that case), so it impossible to init all modules on start.                                                                                                             

It was necessary to use lazy loading modules pattern for logic which required libp2p  (so also for providers like ipfs, orbitdb, storage module).

Some places in the code are already simplified due to the NestJS architecture, but Bartek and I see great potential to further simplify other parts of the code.

However, we are now more focused on completing the overall migration to NestJS and a fully working application, and then focusing on tests

To give You big picture of current progress, we already have operational app with two clients on desktop and mobile and fixing some bugs and errors

**Comment by kingalg** [comment]
Version: 1.4.0-alpha.1
Mobiles and desktops

Full manual QA done on all devices and systems. Everything looks all right.
