### ISSUE TITLE
"You can exit the app" message not true on iOS or desktop

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1642]
Right now users are told "You can exit the app", but this is only true in some cases on Android, and not on desktop.  We need to change this language to make it clear they should keep this screen open.

This is especially important on iOS, as there's almost no chance they'll be able to join successfully without this.

**Comment by kingalg** [comment]
@holmesworcester I came to the same conclusion while checking issue https://github.com/TryQuiet/quiet/issues/1374 and talked about it with Kacper. He told me that changing this text is quick and easy and he can do this if you provide correct text. 

I believe that it would be beneficial to fix this asap as this can stop user from joining community and build frustration with our app from the beginning. 

Instead of telling them that they can exit app we should ask to not close the app until registration is completed.

**Comment by holmesworcester** [comment]
More accurate text is here: https://github.com/TryQuiet/quiet/issues/1374#issuecomment-1655700363

**Comment by holmesworcester** [comment]
@Kacper-RF since this is just a text change and since it's related to an issue in the sprint, I agree with Kinga that we should just fix it now.

**Comment by Kacper-RF** [comment]
I will do it today

**Comment by Kacper-RF** [comment]
https://github.com/TryQuiet/quiet/pull/1679

**Comment by kingalg** [comment]
Version Version: 1.7.1-alpha.0
System - all desktop

Checked on desktop as well. Fixed.
