### ISSUE TITLE
Backend seemed lost, no error dialog, had to restart

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1670]
What happened:

After running Quiet 1.4.0 on desktop for a few days, I stopped receiving new messages, and when I sent messages, they would simply disappear. 

Usually when this happens there is a JavaScript error dialog, but this time there wasn't, and I couldn't see the error in the logs either. 

Sending the logs to Slack.

**Comment by holmesworcester** [comment]
I  got a "channel closed" error when shutting down.

**Comment by holmesworcester** [comment]
@EmiM do we suspect that this issue will be fixed by #2055 ?

**Comment by EmiM** [comment]
What do you mean by " they would simply disappear."? They appeared and disappeared? When user sends message we first display this message on channel so if the message is not displayed that may mean that something is not right on the frontend part. But appearing and disappearing? I am not sure. Maybe frontend logs would be helpful.

About 'ERR_ENCRYPTION_FAILED' - this should not leave quiet app in a broken state because this error is being caught.

> do we suspect that this issue will be fixed by https://github.com/TryQuiet/quiet/issues/2055 ?

If you did not see "abnormal backend termination" message or something else that suggested that this is unhandled error then no.

I still have no idea what happened here, I don't have enough information. We can also wait and check if this even occurs on the newest version because current one is 1.9.6 and you tested this on 1.4.0.

**Comment by holmesworcester** [comment]
>> do we suspect that this issue will be fixed by https://github.com/TryQuiet/quiet/issues/2055 ?
> If you did not see "abnormal backend termination" message or something else that suggested that this is unhandled error then no.

Okay, so let's leave it open as a separate issue. I haven't seen this issue in quite some time so let's close it. 

> What do you mean by " they would simply disappear."? 

I would type a message, hit enter to send, then see no message.
