### ISSUE TITLE
"Join/Create community" and "Username registration" screens are graying out input

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#1677]
**The problem:** 

Right now, if our backend is not yet running, a user cannot start the process of joining or creating a community, because the fields are greyed out. This is bad because it interrupts the first time user experience and appears broken: it is very unusual for users to run into inactive fields in an onboarding flow, so users might assume brokenness. 

**How it should work (ideal solution)**

Users should be able to start the process of joining or creating a community. We shouldn't do anything that requires the backend until they submit. Once they submit their community info (community name or invite) and choose their username, they can see a progress indicator. If the backend is not yet running, the progress indicator can say "Starting backend". 

**How it should work (acceptable solution)**

Instead of showing inactive fields on the join/create screens, we can show our splash screen. Ideally it would include an explanatory note in this phase, e.g. "Starting backend". 

Note: we should not show a splash screen while the backend is starting when when users are returning to an existing community, because this will make the app much less useful on iOS.

**Notes from @siepra:**

It also causes greyed-out input on chat screen and context menu dots on channel list screen to "blink" due to short time between restoring the app and initializing backend services.

In `AppDelegate.m` we use `applicationDidEnterBackground` and `applicationWillEnterForeground` lifecycle callbacks to notify react-native about app state changes but unfortunately the UI operations needs react-native context to be active which makes those callbacks not fully effective (changes to UI are being applied only after fully coming back to foreground which makes components "blink"). In fact, we should be using `applicationWillResignActive` for any UI operations but it turns out it also doesn't reach react-native.

There're two sagas responsible for marking UI ready and performing redirections: `onConnectedSaga` and `redirectionSaga` but they do well for initial redirections and are not aware of app changing it's state between active and idle

**Comment by holmesworcester** [comment]
@Kacper-RF is this something we can work on without @siepra and @vinkabuki ?

**Comment by holmesworcester** [comment]
Also, probably what should happen here is that users should be able to open/paste an invite link and choose a username, and then "starting backend" should become part of the progress when users are joining.

**Comment by Kacper-RF** [comment]
Maybe some quick fix for a better UX would not be to gray out the input but to disable the submit button?

**Comment by EmiM** [comment]
How this task corresponds with https://github.com/TryQuiet/quiet/issues/1657?
Should we have a splashscreen? Your last comment here says something about progress indicator but I think we were talking about getting rid of it?

We need designs and very precise description on how starting application should look like on each OS. This is necessary not only for dev team but also for Kinga so she could accept or reject changes.

**Comment by EmiM** [comment]
@holmesworcester could you write your decisions/propositions here?

**Comment by holmesworcester** [comment]
Okay, so I think the principles are:

1. Users should only have to wait when absolutely necessary.
2. Wait times should be as short as possible. 
3. Users should see informative status when they're waiting.
4. ...Unless any of these would add an uncomfortable amount of complexity. Then we can defer it.

You'll have to be the judges of 4, but here's my ideal picture of how joining goes:

1. Backend begins starting. 
2. User should see our own splash screen on iOS, not "powered by react native"
4. In the case where the app has opened because a user opened an invite link. If so, we start connecting to the network immediately.
5. In the case where the user has opened the app directly without opening an invite link, users should be able to paste an invite link immediately, continue, and choose a username.
6. If users have to wait for more than 1 or 2 seconds to see the join/create screens, we should show a spinner or progress bar.
7. Users should be able to create a community and choose a username instantly too.
8. We should avoid any delay or CPU-intensive work between pasting a link and choosing a username, since this can take a lot longer on mobile than on desktop and create a bad experience. Any CPU intensive stuff like generating keys should happen after the user picks a username. (vinkabuki just worked on this) 
9.  The joining process can take a while, so we should show informative progress when we are joining a community. If Tor has not started yet, we can show Tor startup process. If syncing is taking a while we should show syncing progress.

What we should do for different wait times (general guidelines -- source: https://blog.prototypr.io/guidelines-for-time-indication-and-progress-bars-in-user-interaction-design-4d5038084c84) 
):

0–2 Seconds = No Indication Needed (generally instantaneous to the user)
2–5 Seconds = Busy Animation, Spinner or Spinning Animation
5-X Seconds = Progress Indication Needed, Progress Bar or Visual Indication of Start & Finish (Note: A textual indication of the time remaining is generally recommended in these scenarios.)
10+ Seconds = Progress Indication & Cancel Button, User Should Have Ability to Cancel the Process (Note: A textual indication of the time remaining is strongly recommended in these scenarios.)

Unfortunately we can't show "time remaining" on joining because we really don't know.

**Comment by holmesworcester** [comment]
@EmiM I updated the ticket description. Can you confirm that it is sufficiently clear?

**Comment by siepra** [comment]
To see the full picture, let's divide our logic holding objects (sagas) into two categories:

- the ones making changes to the local storage
- the ones emitting websocket events to backend

While the first ones can be fully operative on their own, the seconds ones requires backend to be up and running. 
There are two conditions that has to be met in order to be able to interact with backend:

- web socket client must be connected
- current community must be initialized
 
Information about the web socket client connection status can only be reached directly from within `mobile`/`desktop` package (unless someone knows the way to pass the local selector value up to `state-manager`).

Unfortunately, we share the vast majority of the second-type sagas in `state-manager` package which means it's hard to suspend its execution until backend becomes operative (for the reason I mentioned above, and also for the fact that changes made to `state-manager` affects `mobile` and `desktop` equally)

So all the possible solutions have their pros and cons:

1. Block the inputs until backend's ready

- pro: probably the most error resistant solution
- con:  frontend doesn't become immediately interactive

2. Use splash screen on app start

- pro: reduces complexity related to blocking inputs/buttons
- con: slows down the app by blocking frontend (iOS is especially vulnerable)

3. Proxy `state-manager` action dispatches through local sagas

- pro: enhances UX
- con: introduces more complexity and duplication of code

4. Suspend execution of `state-manager` sagas until backend becomes operative

- pro: the most "clean" solution
- con: there's no clear way of how to achieve it (may be time consuming or even impossible)

Let me know what you think about it. Also don't hesitate to share some other ideas

@holmesworcester @vinkabuki @Kacper-RF

**Comment by holmesworcester** [comment]
Because this issue is focused on the join/create screen, maybe the solution is to show our splash screen until these fields are available, but don't show a place screen when the user is returning to an already joined community.

Does this make sense?

**Comment by holmesworcester** [comment]
Why will showing the splash screen conditionally on join/create screens not improve anything? It seems to be a solution to the problem, i.e. "inactive fields are unexpected and seem broken, so don't show inactive fields".

The way I picture doing it is, add something to the frontend so that instead of showing inactive fields we show something that looks just like our splash screen.

Anyway, a solution to this ticket simply requires not showing grey / inactive fields to the user on the join/create screens without making any other parts of the app worse.

**Comment by siepra** [comment]
RE: _Anyway, a solution to this ticket simply requires not showing grey / inactive fields to the user on the join/create screens without making any other parts of the app worse._

It doesn't really corresponds to what you've said earlier:

- _Right now, if our backend is not yet running, a user cannot start the process of joining or creating a community, because the fields are greyed out [...] Users should be able to start the process of joining or creating a community. We shouldn't do anything that requires the backend until they submit._

- _Join/create screens visible ASAP_

- _Users should be able to create a community and choose a username instantly with no delays_

That's why I claim splash screen won't actually improve anything. It'd only be an alternative way of doing what we already do.

**Comment by holmesworcester** [comment]
Sure, I can change the description.

From your description of the challenge involved in knowing when we can submit to backend, the part that is not clear to me is why we can't retry submission every second until we get a response.

**Comment by holmesworcester** [comment]
Description updated! Looks good? @siepra

**Comment by siepra** [comment]
RE: _why the frontend can't retry submission every second until it gets a response,_

That's because it's not frontend (mobile/desktop) but `state-manager` that actually talks to the backend.
Here is the sample code of what it should look like to work like you said (and like I would prefer it to work):

```
// packages/state-manager

export function emitEvent() {
    while (true) {
        const ready = yield* select(initSelectors.ready) // web socket client is conneted (&other conditions)
        if (ready) {
           yield* call(socket, socket.emit)
           break
       }
    }
}
```

The problem is `ready` is not reachable within `state-manager`.
We would be able to wrap it into yet another frontend saga:

```
// packages/mobile

import { emitEvent } from '@quiet/state-manager'

while (true) {
    const ready = yield* select(initSelectors.ready)
    if (ready) {
        yield* call(emitEvent)
    }
}

```

Although it means we'd be calling local sagas instead of state-manager directly which would be different from what we do in desktop's containers, and the only responsibility of that sagas would be to suspend event emitting (messy)

**Comment by siepra** [comment]
https://github.com/TryQuiet/quiet/assets/15381135/bde51631-7185-4bd0-8dd1-d1a6242e2481

**Comment by holmesworcester** [comment]
Looks great.
