### ISSUE TITLE
Notification permission not requested on startup

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1710]
Steps to reproduce:
1. Install Quiet from Play Store (1.4.1-alpha.2)
2. Join a community

Expected: Quiet requests notification permissions
Actual: no request is made and notifications are off by default

**Comment by holmesworcester** [comment]
@kingalg @siepra was this fixed? is this a duplicate?

**Comment by kingalg** [comment]
@holmesworcester I think it's a duplicate because I remember checking it. I just had a look at this again, and it's even on our prod version. It does ask when the user is installing the app, not at the point of joining a community like you suggested, but for me, it's an even better place. So, if you agree, Holmes, I'm going to close it. 

![share_3871456075811454537](https://github.com/TryQuiet/quiet/assets/68909168/dfa093d6-263f-4e52-870e-79ef86779ab0)
