### ISSUE TITLE
Not able to install Quiet on Windows when username includes spaces

### ISSUE THREAD

**Issue by MinhTriHoang** [TryQuiet/quiet#1966]
so I got this error when trying to run the quiet.exe (on windows):
![image](https://github.com/TryQuiet/quiet/assets/102776744/7c7531ac-903e-4c88-94c1-2f0e2b4b1fd3)

**Comment by holmesworcester** [comment]
Thanks! Can you include the logs from the command line as well?

**Comment by MinhTriHoang** [comment]
Yes this is the logs from the command line I just saved to notepad in case:
![image](https://github.com/TryQuiet/quiet/assets/102776744/96429da7-af0d-4d54-b5fd-5d695214d8b1)

**Comment by leblowl** [comment]
Thanks @MinhTriHoang !

> 'C:\Users\Hoang' is not recognized as an internal or external command, operable program or batch file.

It looks like perhaps the space in the file path is causing an issue. Very interesting. If that's the case, then it might be an easy fix.

**Comment by kingalg** [comment]
@holmesworcester @leblowl I confirm that it's because of a space with username of the Windows user. I reproduced it on my computer on user created specifically to check this and @vinkabuki did the same on his computer confirming to me that the issue is indeed where Lucas suggested it can be.
![IMG_20231115_135650](https://github.com/TryQuiet/quiet/assets/68909168/1e95aa44-e0eb-4faa-a0d2-d4abe9decdbb)

**Comment by holmesworcester** [comment]
Great. We should fix this ASAP!

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/2123

**Comment by kingalg** [comment]
desktop@2.1.0-alpha.0
System: Windows

Fixed.
