### ISSUE TITLE
User should be able to see profile images

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2066]
User should be able to see profile images created on desktop, on mobile. Creating is covered in #2065 

It's important that this does not hurt scroll performance.

See: https://github.com/TryQuiet/quiet/issues/615

**Comment by leblowl** [comment]
Users should already be able to see images on mobile, just not edit them.

**Comment by kingalg** [comment]
desktop@2.1.1-alpha.0
mobile@2.1.1-alpha.0 | iOS 350

Profile images of users who have added their profile picture on the desktop are visible on mobile. Scroll performance was not impacted on any of my desctop and mobile devices. (As there is no possibility of seeing a profile on a mobile so I assume that what this issue is about is seeing profile pictures in the conversations on channels.)
