### ISSUE TITLE
[EPIC / DRAFT] Users can join a community with a manually-created invite link.

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2267]
We want Quiet to work as well as WhatsApp, Telegram, or Signal on iOS, even in a small network of only iOS clients. This will require help from a server, given iOS restrictions on p2p. The first and most important way this server can be useful on iOS is to facilitate joining a community. 

One minimal first step is to get to a point where users can join a community with a manually-created invite link. That is, we've put data on a server at some URL, and we can use this URL in an invite link. (Eventually these invite links will be automatically generated and uploaded to a store and forward service provided by us or the user, but we can get the basic functionality working without worrying about the server yet.) 

Here’s one proposal for splitting this work into smaller steps or releasable chunks. _(We might not split the work up in exactly this way, but we want to split it up into as many small, releasable pieces as possible.)_

1. Specify a file format for invite data that can contain community metadata and history (maybe this is just OrbitDB/IPFS blocks)
2. Create a reference file for testing
3. Quiet can parse this file, join a community, and display history (no UI)
4. Quiet can generate an invite file for a given community (no UI)
5. Quiet can generate an invite file and host it on  a Tor onion service (no UI)
6. Quiet can open an invite link of this type (file, hosted on a Tor onion service) in addition to existing 2.x invite links.
7. Quiet can generate an invite link of this type (file, hosted on a Tor onion service)
8. Quiet can open an invite link that points to either a Tor onion service, a store and forward server, or both. 
9. Quiet can no longer open 2.x invite links

At this point, iOS users can join a community with manually uploaded, manually generated invite links, and see history. From here, our next epic might be to let individual users generate invite links using a community's store and forward service, provided one has been added manually. After that we can let users register with our store and forward service on community registration, or add their own. At that point we've made joining fast and reliable for iOS users. 

We might not split the work up in exactly this way, but we want to split it up into as many releasable pieces as possible.

**Comment by siepra** [comment]
> One minimal first step is to get to a point where users can join a community with a manually-created invite link

This sounds to me rather like a very advanced stage of developing this whole new ecosystem, skipping many important milestones we have to reach along the way. I can point out other, smaller, intermediate steps, eg:

The first step may be **"Establish basic (essential) server infrastructure"**:
1. Design a server
What technologies to use?
How to serve multiple communities (it's important because we need to come up with scalable solution, otherwise we'll end up having to redesign and refactor the whole thing)?
How to store and point to the right data source?
What endpoints do we need?

2. Choose infrastructure
Where does the server live?
How does the client (the one creating an invite link) know the server URL?

The second step may be **"Enable client to get aid from the server"**:
1. Utilise API on the client side
What layer and language do we want to use for the implementation?
What security mechanism do we want to include (auth tokens, checksums etc.)

The third step may be **"Server assists joining the community"**:
1. Design data structure

2. Adjust existing client joining mechanism
What refactoring are necessary?
How do we preserve joining dualism (with and without server assistance)?

The fourth step may be **"A community member can generate an invite link using the server aid feature"**

Each of those steps must be split up into several tasks, which would probably form separate sprints. They're also releasable even though they won't expand app's functionality a lot at first. Although, we'll be able to track down regressions early.
We can minimise the amount of work by using mocked data set before reaching the last step.
By fulfilling those four steps we'll actually get to the point you described, or at least that's how I see it.

**Comment by EmiM** [comment]
I don't fully understand the "manually-created" part in this context. What do you mean? Would it be a mocked data? How one would create this?

**Comment by holmesworcester** [comment]
> I don't fully understand the "manually-created" part in this context. What do you mean? Would it be a mocked data? How one would create this?

I try to get at this with:

> 1. Specify a file format for invite data that can contain community metadata and history (maybe this is just OrbitDB/IPFS blocks)
> 2. Create a reference file for testing

First we decide what the data should look like. (I think the answer here is probably a bunch of OrbitDB data, stored as IPFS blocks, but we should put thought into this.) Then we make some reference data. (This could be "all the OrbitDB / IPFS blocks in a simple community with a single message.") We could lift this from a Quiet install or create it manually, whichever is easier.

**Comment by holmesworcester** [comment]
@siepra We would need to design the data structure, yes! Once we have that, I am pretty sure we could put that data anywhere, on S3 or ghpages, and save the design of the server, infrastructure choices, and API for the next epic, where we need to write to the server. 

I think there's a whole other way to think about this too where we design the server we want and validate that it can do the things we want, and then build frontend features against that server. 

In your proposal you do the feature horizontally, building up layers from the bottom. In my proposal you do it vertically, working on all the layers at once to get to some improvement that's actually meaningful (for example, this feature would be meaningful for demo'ing Quiet on iOS at a conference) and then return to all the layers for the next feature. 

This question is really interesting too:

> What layer and language do we want to use for the implementation?

I bet the answer will be, "do everything in the NodeJS client backend layer, and do *some* things in the Notification App Extension layer, in whatever language we find best for that." But maybe not!

**Comment by holmesworcester** [comment]
@siepra I think the questions you ask above are a great staring point. Would you and @EmiM like to propose a set of cards that gets us from these questions to some minimal, releasable feature? This could be in a doc or here in GitHub, whatever seems best. And it doesn't have to be fully fleshed-out cards. A basic outline would be enough to start!

I think 'users can join quickly using the Store and Forward service' is the best feature to aim for first, but I'm open to other ideas too.

**Comment by holmesworcester** [comment]
I think this is all dealt with in the Google Doc. Closing.
