### ISSUE TITLE
[QUESTION] What's the fallback in case of server connection failure?

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2283]
[QUESTION] What's the order of executing actions in terms of joining? Has fetching a file priority over connecting to p2p network? Should it happen simultaneously? If it happens simultaneously what in case peers connect faster than downloading the file?

**Comment by holmesworcester** [comment]
> [QUESTION] What's the order of executing actions in terms of joining? Has fetching a file priority over connecting to p2p network? Should it happen simultaneously? If it happens simultaneously what in case peers connect faster than downloading the file?

We can do whatever is easiest. 

The eventual requirements are:
1. Downloaded file is validated
2. Joining only fails if both sources fail to return a file, or return an invalid file.

**Comment by EmiM** [comment]
How I see that:
* we start fetching the file as soon as we can
* libp2p is started anyway, we have peers addresses in the invitation link (right?) so we can start dialing
* as soon as orbitdb is initialized we can feed it the data from the file

If server fails for some reason or file validation fails and client doesn't get the file for a long time then we fallback to replicating data from other peers because we are trying to connect anyway. 

Extra question: Let's assume that fetching file is failing. In the meantime we connected to someone. Should we continue to try to fetch the file after we already connected and replicated metadata?

@holmesworcester what do you mean by "both sources fail to return a file"? Which both sources? Do you mean both fetching/validating file and connecting to someone? Does it mean that user has to wait on joining screen until he connects to someone?

**Comment by holmesworcester** [comment]
@EmiM the current proposal in the doc is a bit different. We could do it the way you describe, but I'm curious which seems simpler / better to you. Can you read through this section in the doc and let me know if you have any more questions about what is proposed?

https://docs.google.com/document/d/1dWWwthyJAoNl6sRT5oBGFnuNnYJiU8ZEn7W5Cm1zPRI/edit#heading=h.1fd7ohjl5eu1

The main difference in the proposal is that we don't have peer information in the invite link anymore, at all. Invite links work the same over Tor as they do with the server.

**Comment by holmesworcester** [comment]
Also, I just responded to your question in the doc, and added a clarification.

**Comment by EmiM** [comment]
Ok, got it. We don't let user **in** until he gets data from either Server (default) or from Hidden Service (fallback) which will be running on inviter machine?

Does Hidden Service for fallback run on every client or only owner's client? I know that docs say "inviter" but I want to clarify that.

**Comment by holmesworcester** [comment]
Every client, because 'owner only' is much less reliable and less under user control. Like if you invite someone you should be able to guarantee that they can get in by staying online.

**Comment by leblowl** [comment]
Can consider this answered and close?

**Comment by holmesworcester** [comment]
Yes.
