### ISSUE TITLE
[QUESTION] What the signal to display community interface to the user?

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#2284]
Let's say it's the presence of community metadata (and general channel*) in the local storage or database.
We need either an event informing that data has been loaded into the database (can the callback be executed when merging data from file into OrbitDB?) or client asking for data.

*general channel presence is more important for the joining user sends "welcome" message

**Comment by holmesworcester** [comment]
I think the event is "invite data is valid". If it's valid, we can start showing the community. If it's not valid, and we can't connect to the Tor fallback, we show an error.

**Comment by siepra** [comment]
I say we think on the level of implementation. "Invite data is valid" is too general and happens definitely too early (and in completely another layer of the application). Presentation layer has nothing to work with until there's data in the local storage. Now, we need to make sure there's a communication interface for injecting the data and we handle right callbacks. So the question we're trying to answer here is what's the exact event we can listen for before starting with navigation actions. It's important because there're many scenarios, eg. user only just joined, user returns, data has changed, etc.

**Comment by holmesworcester** [comment]
This all sounds right to me! Ideas?

**Comment by holmesworcester** [comment]
We'll address this with cards. Closing.
