### ISSUE TITLE
Mistaken Copyright statement in Electron app?

### ISSUE THREAD

**Issue by Juul** [TryQuiet/quiet#2589]
The website doesn't mention who the Quiet developers are. From the github I'd assume they're all independent open source contributors, but the Electron app says "Copyright 2024 Zbay LLC". 

Are all contributors working/contracting for Zbay LLC or does Zbay LLC require copyright assignment for all contributions? If the answer to both of those questions is no then that copyright statement is wrong or at best only a part of the truth.

Whatever the answer is, it raises the question: What is Zbay LLC, what is its relation to Quiet and who are its owners?

**Comment by holmesworcester** [comment]
@Juul you're correct that this is an error since it doesn't reflect volunteer contributions. Thanks for catching this!

GPT suggests adding "and other contributors" and this sounds right to me. 

To answer the question, "Zbay LLC" is the entity that has done most of the work on Quiet. We're going to change the name of the entity to "A Quiet LLC" soon to avoid confusion. "Zbay" was the name of an earlier and long-gone prototype we did that used Zcash for messaging.

**Comment by holmesworcester** [comment]
Note: before closing this we should also look for any boilerplate copyright statements that are wrong in the same way.

**Comment by kingalg** [comment]
Applied in version - 2.3.3-alpha.1 - checked and released.
