### ISSUE TITLE
Prepare docker container with mobile-dev environment

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#376]

**Comment by siepra** [comment]
Waiting for another sprint

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/quiet/pull/737

**Comment by holmesworcester** [comment]
Notes:

1. Add instructions about rf-lerna to README
2. Add instruction that you need to run npm install and lerna bootstrap before running docker
3. Add an example `docker run` command so that users don't think they can use a relative path
4. Add note about docker requiring sudo in the default install, unless the user does more installation steps
