### ISSUE TITLE
User is being notified about completed download

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#681]

**Comment by holmesworcester** [comment]
![Screenshot 2022-07-13 11 37 57 AM](https://user-images.githubusercontent.com/213678/178776090-389eddb9-7989-454c-a708-63848398427a.png)

This should be "@user sent a file in #holmes" 

![Screenshot 2022-07-13 11 36 43 AM](https://user-images.githubusercontent.com/213678/178776091-4401dfcb-5657-471d-b1d0-67925e319b7f.png)

This should be "@user sent an image in #holmes". Let's remove the "Received image" text because it's not necessary. We don't need to show a notification for when an image download completes. People can wait for the placeholder. Maybe someday in the future we can add a preference to show you the notification for an image only once it's finished downloading. Or maybe we change the default to that. But for now let's only show a notification when receiving the image.  

![image](https://user-images.githubusercontent.com/213678/178777356-e1343dd5-03ad-4ff3-9a13-60900592c7fd.png)

"Downloading status: waiting for connection" should be "Downloading file..."

![image](https://user-images.githubusercontent.com/213678/178777081-69c001a9-78ba-47de-8922-438e8adcdaf0.png)

"Downloading status: completed" should say "Download complete. Click to show file in folder." 

Or if that's too long. "File downloaded. Click to show in folder."

Or if that's too long. "File downloaded. Show in folder."

**Comment by siepra** [comment]
Related PR https://github.com/TryQuiet/monorepo/pull/711

**Comment by siepra** [comment]
https://user-images.githubusercontent.com/15381135/178950970-b8692045-98df-40a7-b902-e4b6690f7dfe.mov

**Comment by kingalg** [comment]
0.9.7-alpha-7

I saw notification on all systems. I have doubts if it's working every time, but in general - it's implemented and it may be that I missed notification a few times not that it wasn't there. I will be looking at this feature carefully but for now - it's implemented and I saw it working on all of the systems that we support.
