### ISSUE TITLE
Sent images from clipboard disappear on restart

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#697]
steps to reproduce:

1. Take a screenshot
2. Paste image from clipboard (not from file) 
3. Send image in message
4. Restart Quiet

Expected: image is still visible
Actual: image is missing. 

![image](https://user-images.githubusercontent.com/213678/177788435-5498b018-ab0f-498d-a797-f986f6525590.png)

**Comment by siepra** [comment]
Solution will probably be included in PR for this issue https://github.com/TryQuiet/monorepo/issues/698

**Comment by siepra** [comment]
> Question: what's the best way to write a regression test for this, to make sure we don't lose track of it in the future?

The answer is: there is no way to test what end user sees because it all depends on what exists under the path which points to the file. Nevertheless combination of unit tests for a. storing the copy of the file in 'our' fixed directory, and b. assigning this 'artificial' path to the media object - will do

**Comment by kingalg** [comment]
v 0.9.7-alpha.3
Fixed.
