### ISSUE TITLE
Big files cannot be drag and dropped for some formats

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#786]
Version: 0.9.7-alpha.6

On Mac, Linux and ChromeOs it's impossible to add bigger files by dragging and dropping them. Dropping is working on Windows only. - **that was initial theory**

**new theory** 
Some formats cant be added regardless of size. So far confirmed that formats that can't be drag and dropped are:

- dmg 
- appimage

**Comment by holmesworcester** [comment]
Googling around, someone seems to have a similar issue and a solution: https://medium.com/@devblog_/electron-drag-drop-maximum-file-size-8c773d4d179a

**Comment by holmesworcester** [comment]
We should also check if there is a similar problem for copy/paste

**Comment by EmiM** [comment]
@kingalg I have troubles reproducing it on Linux - I was able to drop over 3.5GB file into the newest version (0.9.7-alpha.6).

**Comment by kingalg** [comment]
I've edited title and description (leaving initial theory) - most probably we encounter problem with specific file types, not size. 

Why do I thing so?
Can drag and drop:
- 170 rmvb 
- 170 exe
Can not drag and drop:
- 170 dmg
- 300 dmg
- 240 appImage

**Comment by EmiM** [comment]
Turned out that the problem is not related to file size. 
React-dnd sometimes can't read a file type: https://github.com/react-dnd/react-dnd/issues/840 and recently we added logic to ignore drop if the dropped file is a folder, wrongly assuming that only folders don't contain 'type' property.
The fix is to not rely on 'type' and to find other solution for blocking folders.

**Comment by EmiM** [comment]
https://github.com/TryQuiet/quiet/pull/791

**Comment by kingalg** [comment]
0.9.7-alpha.7

It's fixed.
