### ISSUE TITLE
Messages visible in push notifications but not in channel view

### ISSUE THREAD

**Issue by siepra** [TryQuiet/quiet#942]
Sometimes we receive notifications for incoming messages which we don't see in channel page.

I think it may happen due to UI thread freeze (which runs state-manager logic) - we check for messages ids we have, but only on state-manager init and we should probably perform this check on every mobile app resume

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/quiet/pull/951

**Comment by holmesworcester** [comment]
Notes on this: 

1. This was a result of #957 (we weren't verifying signatures before firing a notification) which this fix does not fix.
2. The best solution to this problem is to verify signatures in backend
3. Signature verification was probably failing because we were running verification functions in a webview, and running a webview in a foreground process or worker is not possible, see: https://stackoverflow.com/questions/18865035/android-using-webview-outside-an-activity-context (we should verify this but this seems like the reason)
4. This fix will re-verify unverified messages after the app is active, so that they will eventually be visible in the app, but unverified notifications will still display (until we fix #957)

**Comment by Dinek007** [comment]
yes, sounds right

**Comment by kingalg** [comment]
v 0.8.4

Didn't happen to me in this version.
