### ISSUE TITLE
Public URL for community preview

### ISSUE THREAD

**Issue by eshirv** [TryQuiet/quiet#961]
Hi, our group really loves your architecture design. It is so brilliant.

One thing that would be great is if we could post a URL to our room, so people can view it in a browser without first needing to install anything. [Gitter.im](https://gitter.im) does this really well, but doesn't allow us to own our own data, so we have to put a lot of trust in them not to harm our community.

This can make our community chatroom far more inviting, so new guests can see what they're joining, before needing to install any new, unfamiliar software.

It would be an acceptable compromise if this "guest-only" view lost some of the TOR anonymization for visitors, who can still upgrade to the full client by installing.

**Comment by eshirv** [comment]
Pinging on this again because there was an issue creating this Github account to leave this issue:

1. Github flagged this account because I created it using a disposable email address, showing an error message ("Your account has been flagged. Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.")
2. As a consequence, this issue wasn't visible, and would always return a 404 error even when linked to it directly, when not logged in as me (checked from an incognito browser).
3. I've now fixed this issue with GitHub, by adding a new email address and waiting a week for their support reps to remove the flag, and this issue thread now looks visible for all.

But I suspect it failed to send a notification the first time, so writing this note to document what happened.

----

Perhaps it's also useful to document Github's stated policy against temp email addresses, which seems especially relevant for this project:

1. Initial
<img width="637" alt="Screen Shot 2022-10-20 at 4 59 51 PM" src="https://user-images.githubusercontent.com/115525129/197081431-9476fccc-9733-47bd-8564-a63d45d1aaea.png">


2. My followup

![image](https://user-images.githubusercontent.com/115525129/197081697-eb7ccd9a-e2c9-43f5-820c-66b84520a44b.png)



3. Finally resolved, 10 days later

![image](https://user-images.githubusercontent.com/115525129/197081499-d9bbce5c-cd07-4f8c-b959-774b4af3c754.png)

**Comment by holmesworcester** [comment]
@eshirv I am *so* sorry for the absurdly slow reply! On top of the issue you had with Github, this issue got buried in our own internally-created issues. 

We'd be very interested in building this feature for you. Another early user of Quiet (@pdurbin) requested something similar. 

> One thing that would be great is if we could post a URL to our room, so people can view it in a browser without first needing to install anything. [Gitter.im](https://gitter.im/) does this really well, but doesn't allow us to own our own data, so we have to put a lot of trust in them not to harm our community.

> This can make our community chatroom far more inviting, so new guests can see what they're joining, before needing to install any new, unfamiliar software.

Where would this data ideally live? Here are some possibilities:

0. **Onion service / Tor gateway** Quiet could let communities collectively host a hidden service that displayed a similar messaging interface to the one in Quiet. This could be read-only or it could let users send messages via guest accounts. Someone in your community would need to be online for this to work. If users didn't have Tor, they could access it through  a Tor gateway such as [Tor2Web](https://www.tor2web.org/), or you or someone else could run such a gateway. You could also run a gateway with caching enabled.  
1. **Github Pages** Quiet could let one or more users in your community add a Github auth token to Quiet and Quiet could post the latest logs (potentially over Tor) to a git repo that was displayed publicly on Github Pages. I think Github Pages is not so aggressively rate limited and you could do many updates each hour. The group's conversations could be indexed by search engines (if this was desirable). We could also make it work with Gitlab Pages.  
2. **IPFS pinning service** We could post your team's logs to some IPFS pinning service and you could link to it through an IPFS gateway. 
3. **Cloud/web gateway to Quiet that you run** We could build a version of Quiet that ran as a NodeJS application (directly or in a docker container, say) joined your community, and displayed the latest messages. If we chose this path, we could also make it so that users could post with temporary guest accounts and participate actively in the community. You'd have to keep it running and keep it updated.
4. **Cloud gateway that we run** We could offer this as a service with a free plan. I don't think this is what you want, but I'm listing it as an option just in case! 

Which of these directions seems best? I can imagine a bunch of variations on these too, and I'm curious what you'll think of this.

Again, I very much hope you see this reply!

**Comment by holmesworcester** [comment]
Closing

**Comment by pdurbin** [comment]
This issue was pretty close to expressing my needs but it makes sense to close it if @eshirv isn't interested.

@holmesworcester I hope you don't mind but I went ahead and created a fresh issue in my own words:

- #1776

**Comment by holmesworcester** [comment]
The idea of a public archive totally makes sense as its own issue!
